---
- name: Deploying {{ tower_job_template_name }} Component to {{ dep_env }}
  hosts: "{{ tower_job_template_name }}_{{ dep_env }}_{{ server_type }}"
  vars_files:
    - roles/common/vars/linux_common.yml

  pre_tasks:

  vars:
  - published_artifact_url: "NON_ARTIFACT_DEPLOYMENT"
  roles:
  - { role: common, osType: linux }

  tasks:
    - block:

      - name: Apache MW stop start restart deployment
        import_role:
          name: linuxMWApacheServer
        tags: always

  post_tasks:
    - name: Clear facts
      import_role:
        name: clearFacts
      tags: always
