---
- name: "Deploying {{ tower_job_template_name }} Component to {{ dep_env }}"
  hosts: "{{ tower_job_template_name }}_{{ dep_env }}_{{ server_type }}"
  vars_files:
    - roles/common/vars/linux_common.yml

  pre_tasks:

  roles:
  - role: common
    os_type: 'linux' 
    
  tasks:
  - block:
    - name: Setup download temp folder
      import_role:
        name: linuxMWTempDir
      tags: always

    - name: Download artifact from Artifactory
      import_role:
        name: linuxDownloadAndPrep
      tags: always

    - name: Exit if check mode
      meta: end_play
      when: ansible_check_mode

    - name: Find ear files
      import_role:
        name: linuxFindFiles
      vars:
        file_patterns: "*.ear"
      tags: always

    - name: "MW deployment - UNINSTALL App(s) {{ file_name }}"
      vars:
        mw_cmd_args: "UNINSTALL_{{ item }}_{{ cell_code }}"
      include_role:
        name: linux_mw_cmd
        tasks_from: run_mw_cmd
      with_items:
        - "{{ file_name }}"

    - name: "MW deployment - INSTALL App(s) {{ file_name }} "
      vars:
        mw_cmd_args: "INSTALL_{{ item }}_{{ cell_code }}"
      include_role:
        name: linux_mw_cmd
        tasks_from: run_mw_cmd
      with_items:
        - "{{ file_name }}"

    - name: "MW deployment - SYNC cluster(s) -- {{ cell_code }}"
      vars:
        mw_cmd_args: "SYNC_{{ item }}"
      include_role:
        name: linux_mw_cmd
        tasks_from: run_mw_cmd
      with_items:
        - "{{ cell_code }}"

    - name: Set artifact deployed property in Artifactory
      import_role:
        name: setArtDepl
      when: dep_env not in deployed
      tags: always

    always:
    - name: Remove temp directory after deployment    
      import_role:
        name: linuxMWTempDir
        tasks_from: remove_temp_dir.yml
      tags: always

    # conditional for block above
    when: dep_env not in deployed or dep_override

  post_tasks:
  - name: Clear facts
    import_role:
      name: clearFacts
    tags: always
