---

- name: tomcat mw deployment - stop cluster(s)
  import_tasks: MWCluster.yml
  vars:
    mw_cluster_action: STOP

- name: tomcat mw deployment - install
  import_tasks: MWInstall.yml
  vars:
    mw_install_action: INSTALL

- name: execute commands specified in survey variable
  import_tasks: linuxAnsibleScripts.yml

- name: tomcat mw deployment - start cluster(s)
  import_tasks: MWCluster.yml
  vars:
    mw_cluster_action: START
